### ISSUE TITLE
Practica SmartSheet

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-balam#1]
[Práctica SmartSheet.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-balam/files/9882503/Practica.SmartSheet.pdf)

**Comment by carlos-chrs** [comment]
Muy bien Hecho.
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
